language: cpp

compiler:
- g++

env:
  global:
   - secure: "B9LUVx8lPlb15tyMJx9rageSXPK9bu57QGneuzrwxUmQOMIST2K/FI3jtz5qN6MNIwhVqhvFDfdyU+jAHLkYFjZ7LUiGsglU895ouz/LgWhNZVsA7JuUNVB6+rDqC0XdFoNWHAha2lHjOrDAA6vk0xQy7heltUGCromMgsvfYAsxnvFG6rmzWrObrcx7DYc2f+gucL03FUQgdJS7wQl6fMuDyn2tHArk9k/d27Cb0LUrUtLmgRj0CWbiVV6GvnSa/UX3WRvmcJkLM/k8CZ5UOi7J5R9mJMuqYVgddHpu2tAch/8B4WzthqhuyMpovPFidQdBxHM33AMN1ekKS+qE3X+AujxU/yxhpw5gF6tyB9DRw9gKLyY9cLVLX+uot3SClaAXTLROKcVx598oWZhYMT6FnA8MVG3lRMXvs+tDu57RccmZzDQLSmT4YqcsiR0MQtRtNIpe83WtUsU0CyYF0cteiTtIi227uisfsk8H4v61iYGfUCyKtDGWz48rQexdp8djLsuFe58AxoGNd+s6c3k0WxgDz/Sh8M5ths2eV5n1AuQjZ4Rgl26bupoIvs+99+/mhfQbi4YD1VX93wVlq6trnonJcD5fbGjsoW37XoW0iyuAuFPnMjM9oQw8uzep3Fi/CLHNpvXJxce4sQPRu08YtNqJsNCiRFi4/B0nBsQ="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

notifications:
  email:
    on_success: never
    on_failure: never

before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- git clone https://github.com/Bang3DEngine/Bang
- cd Bang

install:
- sudo apt-get update
- sudo apt-get -y install cmake make autoconf automake libtool git autogen build-essential libegl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev zlib1g-dev libsndfile1-dev libsndio-dev
- sudo apt-get -y install -qq g++-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

addons:
  coverity_scan:
    project:
      name: "Bang3DEngine/Bang"
      description: "Description"
    notification_email: ""
    build_command_prepend: "mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=ON -DFROM_TRAVIS=ON -DCMAKE_BUILD_TYPE=Release .."
    build_command: "make VERBOSE=1 -j6"
    branch_pattern: coverity_scan

script:
# - rm -rf build && mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DFROM_TRAVIS=ON -DCMAKE_BUILD_TYPE=Debug   .. && make VERBOSE=1 -j6 && cd ..
- rm -rf build && mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DFROM_TRAVIS=ON -DCMAKE_BUILD_TYPE=Release .. && make VERBOSE=1 -j6 && cd ..
- sudo apt-get -y install libglew-dev libfreetype6-dev libopenal-dev libsdl2-dev libsdl2-ttf-dev libassimp-dev
# - rm -rf build && mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=ON -DFROM_TRAVIS=ON -DCMAKE_BUILD_TYPE=Debug   .. && make VERBOSE=1 -j6 && cd ..
- rm -rf build && mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=ON -DFROM_TRAVIS=ON -DCMAKE_BUILD_TYPE=Release .. && make VERBOSE=1 -j6 && cd ..
- cd Scripts/BuildPackage && ./buildPackage.sh && cd ../..
