#ifndef LAYOUTSIZETYPE_H
#define LAYOUTSIZETYPE_H

#include "Bang/Bang.h"

NAMESPACE_BANG_BEGIN

enum class LayoutSizeType { NONE, MIN, PREFERRED, FLEXIBLE };

NAMESPACE_BANG_END

#endif // LAYOUTSIZETYPE_H
